"use client";

import {
  DndContext,
  KeyboardSensor,
  PointerSensor,
  closestCenter,
  useSensor,
  useSensors,
  type DragEndEvent,
} from "@dnd-kit/core";
import {
  SortableContext,
  arrayMove,
  sortableKeyboardCoordinates,
  useSortable,
  verticalListSortingStrategy,
} from "@dnd-kit/sortable";
import { CSS } from "@dnd-kit/utilities";
import { useEffect, useState } from "react";

import type { TodoDto, TodoStatus } from "@/lib/types";

/** Empty / current / done marker, shared by the read-only and editable rows. */
function StatusDot({ status }: { status: TodoStatus }) {
  if (status === "done") {
    return (
      <span className="flex h-4 w-4 shrink-0 items-center justify-center rounded-full bg-accent text-[10px] text-white">
        ✓
      </span>
    );
  }
  return (
    <span
      className={`h-4 w-4 shrink-0 rounded-full border-2 ${
        status === "doing" ? "border-accent" : "border-line"
      }`}
    />
  );
}

function SortableTodoRow({
  todo,
  onToggleDone,
  onToggleCurrent,
  onRename,
  onRemove,
}: {
  todo: TodoDto;
  onToggleDone: () => void;
  onToggleCurrent: () => void;
  onRename: (title: string) => void;
  onRemove: () => void;
}) {
  const { attributes, listeners, setNodeRef, transform, transition, isDragging } =
    useSortable({ id: todo.id });
  const [text, setText] = useState(todo.title);

  // Follow upstream title changes (e.g. after a reload) when not being edited.
  useEffect(() => {
    // eslint-disable-next-line react-hooks/set-state-in-effect -- syncing local text to props, not a render loop
    setText(todo.title);
  }, [todo.title]);

  const done = todo.status === "done";
  const doing = todo.status === "doing";

  return (
    <li
      ref={setNodeRef}
      style={{ transform: CSS.Transform.toString(transform), transition }}
      className={`flex items-center gap-2 rounded-xl border px-2.5 py-2 ${
        doing ? "border-accent bg-accent-soft/40" : "border-line bg-surface"
      } ${isDragging ? "opacity-60 shadow-sm" : ""}`}
    >
      <button
        type="button"
        {...attributes}
        {...listeners}
        aria-label="Drag to reorder"
        className="shrink-0 cursor-grab touch-none px-1 leading-none text-faint hover:text-muted active:cursor-grabbing"
      >
        ⠿
      </button>

      <input
        type="checkbox"
        checked={done}
        onChange={onToggleDone}
        aria-label={done ? "Mark not done" : "Mark done"}
        style={{ accentColor: "var(--accent)" }}
        className="h-4 w-4 shrink-0"
      />

      <input
        value={text}
        onChange={(e) => setText(e.target.value)}
        onBlur={() => onRename(text)}
        onKeyDown={(e) => {
          if (e.key === "Enter") e.currentTarget.blur();
          if (e.key === "Escape") {
            setText(todo.title);
            e.currentTarget.blur();
          }
        }}
        className={`min-w-0 flex-1 rounded bg-transparent px-1 py-0.5 text-sm outline-none focus:bg-background ${
          done ? "text-muted line-through" : ""
        }`}
      />

      <button
        type="button"
        onClick={onToggleCurrent}
        title={doing ? "You're working on this now" : "Mark as what you're working on now"}
        aria-pressed={doing}
        className={`shrink-0 rounded-full px-2 py-0.5 text-xs font-medium transition-colors ${
          doing
            ? "bg-accent text-white"
            : "text-muted hover:bg-accent-soft/50 hover:text-accent"
        }`}
      >
        {doing ? "Now" : "Start"}
      </button>

      <button
        type="button"
        onClick={onRemove}
        aria-label="Delete sub-task"
        className="shrink-0 px-1 leading-none text-faint hover:text-red-600"
      >
        ✕
      </button>
    </li>
  );
}

/**
 * Task checklist. In editable mode (admin) rows can be checked off, marked as
 * the current focus, renamed inline, dragged to reorder, added, deleted, and
 * regenerated by the AI. In read-only mode (a requester on their own task) it
 * shows the same items and their progress with no controls.
 *
 * Local `items` mirror the server list for instant feedback; every mutation
 * fires the request and then calls onChanged to reconcile with server truth
 * (which also reverts a failed optimistic change).
 */
export function TodoChecklist({
  taskId,
  todos,
  editable,
  canRegenerate,
  onChanged,
}: {
  taskId: string;
  todos: TodoDto[];
  editable: boolean;
  canRegenerate: boolean;
  onChanged: () => void | Promise<void>;
}) {
  const [items, setItems] = useState<TodoDto[]>(todos);
  const [draft, setDraft] = useState("");
  const [adding, setAdding] = useState(false);
  const [regenerating, setRegenerating] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    // eslint-disable-next-line react-hooks/set-state-in-effect -- syncing local list to server truth, not a render loop
    setItems(todos);
  }, [todos]);

  const sensors = useSensors(
    useSensor(PointerSensor, { activationConstraint: { distance: 4 } }),
    useSensor(KeyboardSensor, { coordinateGetter: sortableKeyboardCoordinates }),
  );

  const doneCount = items.filter((t) => t.status === "done").length;

  async function patchTodo(
    id: string,
    patch: { title?: string; status?: TodoStatus },
  ) {
    const res = await fetch(`/api/todos/${id}`, {
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(patch),
    });
    if (!res.ok) setError("That change didn't save.");
    await onChanged();
  }

  function toggleDone(todo: TodoDto) {
    const next: TodoStatus = todo.status === "done" ? "pending" : "done";
    setItems((cur) =>
      cur.map((t) => (t.id === todo.id ? { ...t, status: next } : t)),
    );
    void patchTodo(todo.id, { status: next });
  }

  function toggleCurrent(todo: TodoDto) {
    const next: TodoStatus = todo.status === "doing" ? "pending" : "doing";
    setItems((cur) =>
      cur.map((t) => {
        if (t.id === todo.id) return { ...t, status: next };
        // At most one 'doing' at a time; demote the previous current optimistically.
        if (next === "doing" && t.status === "doing") return { ...t, status: "pending" };
        return t;
      }),
    );
    void patchTodo(todo.id, { status: next });
  }

  async function rename(todo: TodoDto, title: string) {
    const trimmed = title.trim();
    if (!trimmed || trimmed === todo.title) return;
    setItems((cur) =>
      cur.map((t) => (t.id === todo.id ? { ...t, title: trimmed } : t)),
    );
    await patchTodo(todo.id, { title: trimmed });
  }

  async function remove(todo: TodoDto) {
    setItems((cur) => cur.filter((t) => t.id !== todo.id));
    const res = await fetch(`/api/todos/${todo.id}`, { method: "DELETE" });
    if (!res.ok) setError("Could not delete that sub-task.");
    await onChanged();
  }

  async function add(event: React.FormEvent) {
    event.preventDefault();
    const title = draft.trim();
    if (!title) return;
    setAdding(true);
    setError(null);
    const res = await fetch(`/api/tasks/${taskId}/todos`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ title }),
    });
    setAdding(false);
    if (!res.ok) {
      setError("Could not add that sub-task.");
      return;
    }
    setDraft("");
    await onChanged();
  }

  async function regenerate() {
    if (
      items.length > 0 &&
      !window.confirm(
        "Replace the unfinished sub-tasks with fresh AI suggestions? Completed ones are kept.",
      )
    ) {
      return;
    }
    setRegenerating(true);
    setError(null);
    const res = await fetch(`/api/tasks/${taskId}/todos/generate`, {
      method: "POST",
    });
    setRegenerating(false);
    if (!res.ok) {
      const body = (await res.json().catch(() => null)) as { error?: string } | null;
      setError(body?.error ?? "Could not generate sub-tasks.");
      return;
    }
    await onChanged();
  }

  async function onDragEnd(event: DragEndEvent) {
    const { active, over } = event;
    if (!over || active.id === over.id) return;
    const oldIndex = items.findIndex((t) => t.id === active.id);
    const newIndex = items.findIndex((t) => t.id === over.id);
    if (oldIndex === -1 || newIndex === -1) return;
    const reordered = arrayMove(items, oldIndex, newIndex);
    setItems(reordered);
    const res = await fetch(`/api/tasks/${taskId}/todos/reorder`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ ids: reordered.map((t) => t.id) }),
    });
    if (!res.ok) setError("Could not save the new order.");
    await onChanged();
  }

  // Read-only: nothing to show when a requester's task has no checklist yet.
  if (!editable) {
    if (items.length === 0) return null;
    return (
      <section>
        <div className="mb-3 flex items-center gap-2">
          <h2 className="text-sm font-semibold">Sub-tasks</h2>
          <span className="text-xs text-muted">
            {doneCount}/{items.length} done
          </span>
        </div>
        <ul className="space-y-1.5">
          {items.map((t) => (
            <li
              key={t.id}
              className={`flex items-center gap-2.5 rounded-xl border px-3 py-2 text-sm ${
                t.status === "doing"
                  ? "border-accent bg-accent-soft/40"
                  : "border-line bg-surface"
              }`}
            >
              <StatusDot status={t.status} />
              <span className={t.status === "done" ? "text-muted line-through" : ""}>
                {t.title}
              </span>
              {t.status === "doing" && (
                <span className="ml-auto text-xs font-medium text-accent">
                  In progress
                </span>
              )}
            </li>
          ))}
        </ul>
      </section>
    );
  }

  return (
    <section>
      <div className="mb-3 flex flex-wrap items-center justify-between gap-2">
        <div className="flex items-center gap-2">
          <h2 className="text-sm font-semibold">Sub-tasks</h2>
          {items.length > 0 && (
            <span className="text-xs text-muted">
              {doneCount}/{items.length} done
            </span>
          )}
        </div>
        {canRegenerate && (
          <button
            onClick={() => void regenerate()}
            disabled={regenerating}
            className="btn btn-ghost btn-sm"
          >
            {regenerating
              ? "Generating..."
              : items.length > 0
                ? "Regenerate"
                : "Suggest with AI"}
          </button>
        )}
      </div>

      {error && <p className="mb-2 text-sm text-red-600">{error}</p>}

      {items.length > 0 && (
        <DndContext
          sensors={sensors}
          collisionDetection={closestCenter}
          onDragEnd={onDragEnd}
        >
          <SortableContext
            items={items.map((t) => t.id)}
            strategy={verticalListSortingStrategy}
          >
            <ul className="space-y-1.5">
              {items.map((todo) => (
                <SortableTodoRow
                  key={todo.id}
                  todo={todo}
                  onToggleDone={() => toggleDone(todo)}
                  onToggleCurrent={() => toggleCurrent(todo)}
                  onRename={(title) => void rename(todo, title)}
                  onRemove={() => void remove(todo)}
                />
              ))}
            </ul>
          </SortableContext>
        </DndContext>
      )}

      <form onSubmit={add} className="mt-2 flex items-center gap-2">
        <input
          value={draft}
          onChange={(e) => setDraft(e.target.value)}
          placeholder="Add a sub-task"
          className="flex-1 rounded-xl border border-line bg-background px-3 py-2 text-sm outline-none focus:border-accent"
        />
        <button
          type="submit"
          disabled={adding || draft.trim().length === 0}
          className="btn btn-ghost btn-sm"
        >
          {adding ? "Adding..." : "Add"}
        </button>
      </form>

      {items.length === 0 && (
        <p className="mt-2 text-xs text-muted">
          No sub-tasks yet. Add one above
          {canRegenerate ? ", or let the AI suggest a checklist." : "."}
        </p>
      )}
    </section>
  );
}
